baseURL: "https://danalarcon.online/"
languageCode: "es-ES"
title: Second Brain
theme: PaperMod
paginate: 5


enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-Y73BGHXZZV

googleAnalytics = "UG-Y73BGHXZZV"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Daniel
  # author: ["Daniel", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: false # to disable highlight.js
    disableFingerprinting: false
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
    safari_pinned_tab:  "/safari-pinned-tab.svg"

  label:
    text: "En Corto"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "En Corto \U0001F44B"
    Content: Espacio donde he decidido dejar mi "Second Brain", y compartir contigo lo que aprendo, tratando que siempre sea En Corto.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/_DanAlarcon_"
    - name: instagram
      url: "https://www.instagram.com/_danalarcon_/"
    - name: facebook
      url: "https://www.facebook.com/elblogdedaniel"
    - name: strava
      url: "https://www.strava.com/athletes/46796449"

  analytics:
    google:
      SiteVerificationTag: "G-Y73BGHXZZV"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page



  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

languages:                      # 配置多语言
    en:
        languageName: "Spanish"

menu:
  main:
    - identifier: archives
      name: Publicaciones
      url: /archives/
      weight: 10
    - identifier: categories
      name: Categorias
      url: /categories/
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: sobremi
      name: Sobre Mi
      url: https://danalarcon.com
      weight: 40
    - identifier: Buscar
      name: Buscar
      url: /search/
      weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
